spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.port=8089
####### Data-Source Properties #######
# Database connection URL.
spring.datasource.url=jdbc:h2:mem:onlinestore_db
spring.datasource.driverClassName=org.h2.Driver
# Declaration of identifiers used for authentication
spring.datasource.username=sa
spring.datasource.password=

# define whether JPA should initialize the database or not (using true/false values)  
spring.jpa.generate-ddl=true
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
